# Generated by Django 6.1 on 2026-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='guest_email',
            field=models.EmailField(default='guest@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
